[project]
name = "yt-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "comtypes>=1.4.14",
    "flet[all]>=0.80.0",
    "pyinstaller>=6.17.0",
    "yt-dlp[default]>=2025.12.8",
]
